import type { Metadata } from "next";

import "./globals.css";
import Navbar from "./components/Navbar/NavBar";
import Footer from "./components/footer/Footer";

export const metadata: Metadata = {
    title: "Portafolio Web",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.ico",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`flex flex-col antialiased from-gray-800 to-black bg-gradient-to-b min-h-screen `}
            >
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    );
}
